// Copyright 2026 The Flutter Authors.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

class CostService {
  static const Map<String, double> ingredientPrices = {
    'active_dry_yeast': 0.75,
    'all_purpose_flour': 0.50,
    'baby_spinach': 1.99,
    'baking_powder': 0.40,
    'baking_soda': 0.30,
    'balsamic_vinegar': 2.50,
    'bay_leaves': 0.15,
    'beef_stock': 1.80,
    'black_beans': 0.99,
    'black_peppercorns': 0.05,
    'brown_sugar_dark': 0.65,
    'canned_crushed_tomatoes': 1.25,
    'canola_oil': 0.80,
    'canola_oil_spray': 1.50,
    'carrots': 0.45,
    'cayenne_pepper': 0.10,
    'celery_stalks': 0.55,
    'cheddar_block': 3.20,
    'chicken_breast': 4.50,
    'chicken_stock': 1.50,
    'corn_starch': 0.35,
    'corn_tortillas': 0.08,
    'cream_cheese': 2.10,
    'cremini_mushrooms': 2.25,
    'crushed_red_pepper': 0.08,
    'dijon_mustard': 1.20,
    'dried_oregano': 0.12,
    'dried_rosemary': 0.15,
    'dried_thyme': 0.14,
    'firm_tofu': 1.75,
    'flank_steak': 8.99,
    'flour_tortillas': 0.12,
    'fresh_basil': 1.50,
    'fresh_cilantro': 0.99,
    'fresh_lemons': 0.60,
    'fresh_limes': 0.50,
    'fresh_mint': 1.25,
    'fresh_parsley': 0.85,
    'fresh_strawberries': 2.99,
    'fuji_apples': 0.95,
    'garlic_bulbs': 0.50,
    'ginger_root': 1.10,
    'goat_cheese_logs': 3.75,
    'granulated_sugar': 0.45,
    'greek_yogurt': 1.80,
    'green_bell_peppers': 0.85,
    'ground_beef': 5.50,
    'ground_cinnamon': 0.12,
    'ground_cumin': 0.10,
    'ground_nutmeg': 0.15,
    'hass_avocados': 1.25,
    'heavy_whipping_cream': 2.40,
    'jasmine_rice': 0.70,
    'jumbo_shrimp': 12.99,
    'kosher_salt': 0.05,
    'kosher_salt_coarse': 0.06,
    'large_eggs': 0.30,
    'maple_syrup': 4.50,
    'mayonnaise': 1.50,
    'micro_greens': 2.99,
    'mozzarella_logs': 3.99,
    'olive_oil_extra_virgin': 3.50,
    'onion_red': 0.65,
    'panko_breadcrumbs': 1.10,
    'parmesan_cheese': 4.25,
    'penne_pasta': 1.20,
    'pinto_beans': 0.89,
    'pork_shoulder': 4.99,
    'red_bell_peppers': 1.10,
    'red_wine_vinegar': 1.99,
    'roma_tomatoes': 0.75,
    'russet_potatoes': 0.50,
    'salmon_fillets': 10.99,
    'scallions': 0.60,
    'sliced_prosciutto': 5.99,
    'sour_cream': 1.25,
    'soy_sauce': 0.95,
    'sriracha_sauce': 1.75,
    'sweet_paprika': 0.12,
    'thick_bacon': 6.50,
    'tomato_paste': 0.80,
    'unsalted_butter': 2.20,
    'vanilla_extract': 8.50,
    'vegetable_stock': 1.60,
    'white_quinoa': 1.50,
    'white_sugar_powder': 0.60,
    'whole_milk': 1.20,
    'wild_arugula': 2.10,
    'wildflower_honey': 3.99,
    'yellow_onions': 0.50,
  };

  double fetchPrice(String ingredientId, double quantity) {
    final pricePerUnit = ingredientPrices[ingredientId] ?? 0.0;
    return pricePerUnit * quantity;
  }
}
