name: federated_plugin_windows
description: Windows implementation of federated_plugin to retrieve current battery level.
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0-0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: FederatedPluginWindowsPlugin
