name: scavenger_hunt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2-183.0.dev

dependencies:
  flutter:
    sdk: flutter
  firebase_vertexai: ^1.4.0
  http: ^1.3.0
  sqlite3: ^2.7.5
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.31
  firebase_core: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
